apiVersion: v1
kind: ConfigMap
metadata:
  name: mlms-config
data:
  PORT: "6000"
  MONGO_URI: "mongodb://mongo:27017/mlms"
  WEBSOCKET_PORT: "6001"
  DASHBOARD_REFRESH_INTERVAL: "5000"
  DEFAULT_LOG_LEVEL: "INFO"
  METRICS_COLLECTION_INTERVAL: "60"