apiVersion: v1
kind: Service
metadata:
  name: mlms-service
spec:
  type: NodePort
  selector:
    app: mlms
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6000
      nodePort: 30009